n = input('Digite algo: ')
print('O tipo primitivo desse valor é',type(n))
print('É alfanumérico?',n.isalnum())
print('É número?',n.isnumeric())
print('É alfabético?',n.isalnum())
print('Tem espaços?',n.isspace())
print('Está em maúsculas?',n.isupper())
print('Está em minúsculas?',n.islower())
print('EStá capitalizada?',n.isprintable())
